### ISSUE TITLE
Allow multilevel dot notation

### ISSUE THREAD

**Issue by Simon-Le** [Colin-b/layabase#27]
Allow using multiple levels of DictColumn and add them to the parser using dot notation.

**Comment by Colin-b** [comment]
It should already be the case, what's missing ?

**Comment by Simon-Le** [comment]
https://github.com/Colin-b/layabase/blob/develop/layabase/_api_mongo.py#L27

Missing the `{prefix}` before `{field.name}` in 
`_add_query_field(parser, inner_field, f"{field.name}.")`

**Comment by Colin-b** [comment]
Good catch, you can submit a PR for this one if you want. Otherwise I'll see when I have some time

**Comment by Colin-b** [comment]
Fixed in #28
